// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PostGreDbContext.Models;

public partial class MessageDb
{
    public int Id { get; set; }

    public Guid SenderId { get; set; }

    public Guid RecipientId { get; set; }

    public string MessageText { get; set; }

    public bool IsReceived { get; set; }
}