// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PostGreDbContext.Models;

public partial class UserRole
{
    public int Id { get; set; }

    public string UserRoleName { get; set; }

    public virtual ICollection<UserDb> UserDbs { get; set; } = new List<UserDb>();
}