// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PostGreDbContext.Models;

public partial class UserDb
{
    public Guid Id { get; set; }

    public string UserEmail { get; set; }

    public string UserPasswordHash { get; set; }

    public int UserRoleId { get; set; }

    public virtual UserRole UserRole { get; set; }
}